### ISSUE TITLE
execute fail

### ISSUE THREAD

**Issue by nathan-yangling** [MetricsGrimoire/CMetrics#2]
Environment: Ubuntu 18.04
gcc verison: 7.5.0

nathan@ubuntu:~/audio/CMetrics$ ./cmetrics -h -f /home/nathan/S1/s1_app/
  File "./cmetrics", line 190
    print template.format("FILE", "SLOC", "LOC", "FUNCS", "BLANK", "COM.L", "COM.N", "H LEN", "H VOL", "H LEVEL", "H MEN. D.",  "MAXCY",  "MINCY", "AVGCY", "MEDCY", "TOTCY",)
                 ^
SyntaxError: invalid syntax

**Comment by gregoriorobles** [comment]
This is because cmetrics is still thought for Python2. There is a pull request to ge merged that has already addressed this. Could the owners please merge it?

**Comment by nathan-yangling** [comment]
@gregoriorobles     Yes, after manual apply the patch, it works, thanks very much.
